namespace MergerNotes.App.Localization;

public sealed record LocalizedStrings(
    string AppTitle,
    string AppSubtitle,
    string AppCaption,
    string LanguageLabel,
    string LanguageSystem,
    string LanguageEnglish,
    string LanguageChinese,
    string OpenBaseButton,
    string OpenIncomingButton,
    string MergeButton,
    string WorkspaceTitle,
    string BaseBackupTitle,
    string IncomingBackupTitle,
    string MergeResultTitle,
    string OpenBasePickerTitle,
    string OpenIncomingPickerTitle,
    string SaveMergedPickerTitle,
    string BackupFileTypeName,
    string NoBaseLoaded,
    string NoIncomingLoaded,
    string NoMergedBackup,
    string LoadBothToPreview,
    string UntitledNote,
    string EmptyContent,
    string StatusOpenBasePrompt,
    string StatusOpenIncomingPrompt,
    string StatusLoadingBase,
    string StatusLoadingIncoming,
    string StatusBaseLoaded,
    string StatusIncomingLoaded,
    string StatusNeedBoth,
    string StatusChooseOutput,
    string StatusMerging,
    string StatusMerged,
    string StatusFailedLoadBase,
    string StatusFailedLoadIncoming,
    string StatusFailedMerge,
    string SummaryManifest,
    string SummaryDatabaseHash,
    string SummaryDatabaseHashVerified,
    string SummaryDatabaseHashMismatch,
    string SummaryCounts,
    string SummaryLocations,
    string SummaryUserMarks,
    string SummaryNotes,
    string SummaryBlockRanges,
    string SummaryTags,
    string SummaryTagMaps,
    string SummaryBookmarks,
    string SummaryMediaAssets,
    string SummaryInputFields,
    string MergeReport,
    string MergeBaseNotes,
    string MergeIncomingNotes,
    string MergeMergedNotes,
    string MergeAdded,
    string MergeAddedLocations,
    string MergeAddedUserMarks,
    string MergeAddedNotes,
    string MergeUpdatedNotes,
    string MergeAddedBlockRanges,
    string MergeAddedTags,
    string MergeAddedTagMaps,
    string MergeAddedBookmarks,
    string MergeAddedMediaAssets,
    string MergeAddedInputFields,
    string MergeSkippedPlaylistTagMaps);

public static class LocalizedStringsFactory
{
    public static LocalizedStrings Create(AppLanguage language)
        => language == AppLanguage.SimplifiedChinese ? CreateChinese() : CreateEnglish();

    private static LocalizedStrings CreateEnglish()
        => new(
            AppTitle: "MergerNotes",
            AppSubtitle: "合并.jwlibrary笔记",
            AppCaption: "",
            LanguageLabel: "Language",
            LanguageSystem: "System / follow OS",
            LanguageEnglish: "English",
            LanguageChinese: "Simplified Chinese",
            OpenBaseButton: "Open base backup",
            OpenIncomingButton: "Open incoming backup",
            MergeButton: "Merge and export",
            WorkspaceTitle: "Workspace",
            BaseBackupTitle: "Base backup",
            IncomingBackupTitle: "Incoming backup",
            MergeResultTitle: "Merge result",
            OpenBasePickerTitle: "Open JW Library backup",
            OpenIncomingPickerTitle: "Open incoming JW Library backup",
            SaveMergedPickerTitle: "Save merged backup",
            BackupFileTypeName: "JW Library backup",
            NoBaseLoaded: "No base backup loaded yet.",
            NoIncomingLoaded: "No incoming backup loaded yet.",
            NoMergedBackup: "No merged backup yet.",
            LoadBothToPreview: "Load both backups to preview merge results.",
            UntitledNote: "(untitled)",
            EmptyContent: "(empty content)",
            StatusOpenBasePrompt: "Open a base backup to inspect its structure.",
            StatusOpenIncomingPrompt: "Open an incoming backup to compare content.",
            StatusLoadingBase: "Loading base backup...",
            StatusLoadingIncoming: "Loading incoming backup...",
            StatusBaseLoaded: "Base backup loaded.",
            StatusIncomingLoaded: "Incoming backup loaded.",
            StatusNeedBoth: "Load both backups before merging.",
            StatusChooseOutput: "Choose an output file path.",
            StatusMerging: "Merging backups...",
            StatusMerged: "Merged backup created successfully.",
            StatusFailedLoadBase: "Failed to load base backup: {0}",
            StatusFailedLoadIncoming: "Failed to load incoming backup: {0}",
            StatusFailedMerge: "Merge failed: {0}",
            SummaryManifest: "Manifest",
            SummaryDatabaseHash: "Database hash",
            SummaryDatabaseHashVerified: "verified",
            SummaryDatabaseHashMismatch: "mismatch",
            SummaryCounts: "Counts",
            SummaryLocations: "Locations",
            SummaryUserMarks: "UserMarks",
            SummaryNotes: "Notes",
            SummaryBlockRanges: "BlockRanges",
            SummaryTags: "Tags",
            SummaryTagMaps: "TagMaps",
            SummaryBookmarks: "Bookmarks",
            SummaryMediaAssets: "Media assets",
            SummaryInputFields: "Input fields",
            MergeReport: "Merge report",
            MergeBaseNotes: "Base notes",
            MergeIncomingNotes: "Incoming notes",
            MergeMergedNotes: "Merged notes",
            MergeAdded: "Added",
            MergeAddedLocations: "Locations",
            MergeAddedUserMarks: "UserMarks",
            MergeAddedNotes: "Notes",
            MergeUpdatedNotes: "Updated notes",
            MergeAddedBlockRanges: "BlockRanges",
            MergeAddedTags: "Tags",
            MergeAddedTagMaps: "TagMaps",
            MergeAddedBookmarks: "Bookmarks",
            MergeAddedMediaAssets: "Media assets",
            MergeAddedInputFields: "Input fields",
            MergeSkippedPlaylistTagMaps: "Skipped playlist tag maps");

    private static LocalizedStrings CreateChinese()
        => new(
            AppTitle: "MergerNotes",
            AppSubtitle: "合并.jwlibrary笔记",
            AppCaption: "",
            LanguageLabel: "语言",
            LanguageSystem: "系统 / 跟随系统",
            LanguageEnglish: "English",
            LanguageChinese: "简体中文",
            OpenBaseButton: "打开基础备份",
            OpenIncomingButton: "打开导入备份",
            MergeButton: "合并并导出",
            WorkspaceTitle: "工作区",
            BaseBackupTitle: "基础备份",
            IncomingBackupTitle: "导入备份",
            MergeResultTitle: "合并结果",
            OpenBasePickerTitle: "打开 JW Library 备份",
            OpenIncomingPickerTitle: "打开待导入的 JW Library 备份",
            SaveMergedPickerTitle: "保存合并后的备份",
            BackupFileTypeName: "JW Library 备份",
            NoBaseLoaded: "尚未加载基础备份。",
            NoIncomingLoaded: "尚未加载导入备份。",
            NoMergedBackup: "尚无合并后的备份。",
            LoadBothToPreview: "同时加载两个备份后可预览合并结果。",
            UntitledNote: "（未命名）",
            EmptyContent: "（空内容）",
            StatusOpenBasePrompt: "打开基础备份以查看其结构。",
            StatusOpenIncomingPrompt: "打开导入备份以比较内容。",
            StatusLoadingBase: "正在加载基础备份...",
            StatusLoadingIncoming: "正在加载导入备份...",
            StatusBaseLoaded: "基础备份已加载。",
            StatusIncomingLoaded: "导入备份已加载。",
            StatusNeedBoth: "请先同时加载两个备份，再执行合并。",
            StatusChooseOutput: "请选择输出文件路径。",
            StatusMerging: "正在合并备份...",
            StatusMerged: "已成功创建合并后的备份。",
            StatusFailedLoadBase: "加载基础备份失败：{0}",
            StatusFailedLoadIncoming: "加载导入备份失败：{0}",
            StatusFailedMerge: "合并失败：{0}",
            SummaryManifest: "清单",
            SummaryDatabaseHash: "数据库哈希",
            SummaryDatabaseHashVerified: "已验证",
            SummaryDatabaseHashMismatch: "不匹配",
            SummaryCounts: "统计",
            SummaryLocations: "位置",
            SummaryUserMarks: "高亮",
            SummaryNotes: "笔记",
            SummaryBlockRanges: "块范围",
            SummaryTags: "标签",
            SummaryTagMaps: "标签映射",
            SummaryBookmarks: "书签",
            SummaryMediaAssets: "媒体资源",
            SummaryInputFields: "输入字段",
            MergeReport: "合并报告",
            MergeBaseNotes: "基础笔记",
            MergeIncomingNotes: "导入笔记",
            MergeMergedNotes: "合并后笔记",
            MergeAdded: "新增",
            MergeAddedLocations: "位置",
            MergeAddedUserMarks: "高亮",
            MergeAddedNotes: "笔记",
            MergeUpdatedNotes: "更新笔记",
            MergeAddedBlockRanges: "块范围",
            MergeAddedTags: "标签",
            MergeAddedTagMaps: "标签映射",
            MergeAddedBookmarks: "书签",
            MergeAddedMediaAssets: "媒体资源",
            MergeAddedInputFields: "输入字段",
            MergeSkippedPlaylistTagMaps: "跳过的播放列表标签映射");
}
